### ISSUE TITLE
Renovate front end.

### ISSUE THREAD

**Issue by UsamaMalick** [CoalAI/CoalDev#4]
Place reasonable Content.
Remove irrelevant information and dummy data.

**Comment by UsamaMalick** [comment]
@MKRNaqeebi  is this header size enough? I decrease the height of logo. I will change the logo text colour as well.

![Screenshot 2020-08-05 at 5 14 30 PM (2)](https://user-images.githubusercontent.com/39711208/89411641-35939f80-d73f-11ea-8051-fdd1b065a213.png)

**Comment by MKRNaqeebi** [comment]
yes good

**Comment by UsamaMalick** [comment]
Logo with white text and black icon.

![logo](https://user-images.githubusercontent.com/39711208/89515195-3afcf280-d7f0-11ea-8c6a-1fe6223bc44e.png)

**Comment by UsamaMalick** [comment]
-1
CoalDev Logo text changes to white and size is adjusted.
![Screenshot 2020-08-06 at 2 28 51 PM](https://user-images.githubusercontent.com/39711208/89516105-70eea680-d7f1-11ea-9fd1-4672dd4dde68.png)

**Comment by UsamaMalick** [comment]
-2
![Screenshot 2020-08-06 at 2 29 11 PM](https://user-images.githubusercontent.com/39711208/89516154-85cb3a00-d7f1-11ea-928c-7395f03b3f59.png)

**Comment by UsamaMalick** [comment]
-3
Provided Services Content has been written successfully.
![Screenshot 2020-08-06 at 2 29 23 PM](https://user-images.githubusercontent.com/39711208/89516208-94b1ec80-d7f1-11ea-915f-074e60403385.png)

**Comment by UsamaMalick** [comment]
-4
There is a slider in below images, Code of hover effect to access link has been comment out.
![Screenshot 2020-08-06 at 2 29 48 PM](https://user-images.githubusercontent.com/39711208/89516246-a1364500-d7f1-11ea-8187-398f5f316b81.png)

**Comment by UsamaMalick** [comment]
-5
These are the team member images approved by @usama2762 
![Screenshot 2020-08-06 at 2 30 01 PM](https://user-images.githubusercontent.com/39711208/89516308-b4e1ab80-d7f1-11ea-9d0d-a8f9bbaf97b2.png)

**Comment by UsamaMalick** [comment]
-6
Leave the footer as it is for now, as suggested by @MKRNaqeebi .
![Screenshot 2020-08-06 at 2 30 07 PM](https://user-images.githubusercontent.com/39711208/89516411-d773c480-d7f1-11ea-8ef7-dc32e7a170e7.png)


My Suggestion for the new footer is:
![1952dca0-b622-47f3-accb-d393ea77b2b5](https://user-images.githubusercontent.com/39711208/89516521-fa05dd80-d7f1-11ea-9a86-7379666c4bdf.jpg)
